# Generated by Django 5.0.6 on 2024-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_model',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
